--------------------------------------------------------
--  파일이 생성됨 - 금요일-7월-16-2021   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table ANIMAL
--------------------------------------------------------

  CREATE TABLE "KH"."ANIMAL" 
   (	"ANIMAL_NO" NUMBER, 
	"AGE" VARCHAR2(1000 BYTE), 
	"CAREADDR" VARCHAR2(1000 BYTE), 
	"CARENM" VARCHAR2(1000 BYTE), 
	"CARETEL" VARCHAR2(1000 BYTE), 
	"CHARGENM" VARCHAR2(1000 BYTE), 
	"COLORCD" VARCHAR2(1000 BYTE), 
	"DESERTIONNO" VARCHAR2(1000 BYTE), 
	"FILENAME" VARCHAR2(1000 BYTE), 
	"HAPPENDT" VARCHAR2(1000 BYTE), 
	"HAPPENPLACE" VARCHAR2(1000 BYTE), 
	"KINDCD" VARCHAR2(1000 BYTE), 
	"NEUTERYN" VARCHAR2(1000 BYTE), 
	"NOTICEEDT" VARCHAR2(1000 BYTE), 
	"NOTICENO" VARCHAR2(1000 BYTE), 
	"NOTICESDT" VARCHAR2(1000 BYTE), 
	"OFFICETEL" VARCHAR2(1000 BYTE), 
	"ORGNM" VARCHAR2(1000 BYTE), 
	"POPFILE" VARCHAR2(1000 BYTE), 
	"PROCESSSTATE" VARCHAR2(1000 BYTE), 
	"SEXCD" VARCHAR2(1000 BYTE), 
	"SPECIALMARK" VARCHAR2(1000 BYTE), 
	"WEIGHT" VARCHAR2(1000 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C007439
--------------------------------------------------------

  CREATE UNIQUE INDEX "KH"."SYS_C007439" ON "KH"."ANIMAL" ("ANIMAL_NO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table ANIMAL
--------------------------------------------------------

  ALTER TABLE "KH"."ANIMAL" ADD PRIMARY KEY ("ANIMAL_NO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
