DROP TABLE ANI_USER;
CREATE TABLE ANI_USER(
	MYNO NUMBER CONSTRAINT PK_ANI_USER_MYNO PRIMARY KEY,
	MYID VARCHAR2(500) NOT NULL,
	MYPW VARCHAR2(500) NOT NULL,
	MYNAME VARCHAR2(1000) NOT NULL,
	MYADDR VARCHAR2(4000) NOT NULL,
	MYPHONE VARCHAR2(20) NOT NULL,
	MYEMAIL VARCHAR2(100) NOT NULL,
	MYROLE VARCHAR2(50) NOT NULL,
	CONSTRAINT UQ_ANI_USER_MYID UNIQUE(MYID),
	CONSTRAINT UQ_ANI_USER_PHONE UNIQUE(MYPHONE),
	CONSTRAINT UQ_ANI_USER_EMAIL UNIQUE(MYEMAIL)
);

COMMENT ON COLUMN ANI_USER.MYNO IS '회원등록번호';
COMMENT ON COLUMN ANI_USER.MYID IS '회원아이디';
COMMENT ON COLUMN ANI_USER.MYPW IS '회원비밀번호';
COMMENT ON COLUMN ANI_USER.MYNAME IS '회원이름';
COMMENT ON COLUMN ANI_USER.MYADDR IS '회원거주지';
COMMENT ON COLUMN ANI_USER.MYPHONE IS '회원연락처';
COMMENT ON COLUMN ANI_USER.MYEMAIL IS '회원이메일';
COMMENT ON COLUMN ANI_USER.MYROLE IS '운영자/일반회원';

INSERT INTO ANI_USER
VALUES(1,'김길동','1234','김길동','서울특별시 강남구 서초동','010-1234-5679','123@abc.kr','일반회원');
INSERT INTO ANI_USER
VALUES(2,'ADMIN','1234','김운영','서울특별시 강남구 역삼동','010-1234-5678','admin@abc.kr','운영자');
