DROP TABLE REPLY_ON_LOSTDETAIL;--실종 상세보기 게시판의 답변

CREATE TABLE REPLY_ON_LOSTDETAIL(
	BOARD_ID NUMBER NOT NULL,
	REPLY_ORDER   NUMBER CONSTRAINT PK_REPLY_ORDER PRIMARY KEY,
	NUM       NUMBER NOT NULL,
	LEV    NUMBER,
	LEV_SEQ NUMBER NOT NULL,
	DEPTH   NUMBER DEFAULT NULL,--루트노드기준을 잡기 위함
	REPLYTAB NUMBER NOT NULL,
	ID       VARCHAR(500) NOT NULL,
	CONTENT  VARCHAR(2000) NOT NULL,
	REGDATE DATE DEFAULT SYSDATE,
	DEL_FLAG NUMBER  DEFAULT 0--0:삭제X 1:삭제O
);

SELECT * FROM REPLY_ON_LOSTDETAIL;

SELECT * FROM (SELECT ROWNUM RPROW, BOARD_ID, REPLY_ORDER, NUM, LEV, LEV_SEQ, REPLYTAB, ID, CONTENT, REGDATE FROM (SELECT * FROM REPLY_ON_LOSTDETAIL)) WHERE RPROW BETWEEN 1 AND 30;

INSERT INTO REPLY_ON_LOSTDETAIL
VALUES(1,1,1,0,1,NULL,0,'ADMIN','테스트글1','21/06/01',0);
INSERT INTO REPLY_ON_LOSTDETAIL
VALUES(1,2,2,0,1,NULL,0,'ADMIN','테스트글2','21/06/01',0);
INSERT INTO REPLY_ON_LOSTDETAIL
VALUES(1,3,3,0,1,NULL,0,'ADMIN','테스트글3','21/06/01',0);
INSERT INTO REPLY_ON_LOSTDETAIL
VALUES(1,4,4,0,1,NULL,0,'ADMIN','테스트글4','21/06/01',0);
INSERT INTO REPLY_ON_LOSTDETAIL
VALUES(1,5,5,0,1,NULL,0,'ADMIN','테스트글5','21/06/01',0);
INSERT INTO REPLY_ON_LOSTDETAIL
VALUES(1,6,6,0,1,NULL,0,'ADMIN','테스트글6','21/06/01',0);
INSERT INTO REPLY_ON_LOSTDETAIL
VALUES(1,7,7,0,1,NULL,0,'ADMIN','테스트글7','21/06/01',0);
INSERT INTO REPLY_ON_LOSTDETAIL
VALUES(1,8,8,0,1,NULL,0,'ADMIN','테스트글8','21/06/01',0);
INSERT INTO REPLY_ON_LOSTDETAIL
VALUES(1,9,9,0,1,NULL,0,'ADMIN','테스트글9','21/06/01',0);
INSERT INTO REPLY_ON_LOSTDETAIL
VALUES(1,10,10,0,1,NULL,0,'ADMIN','테스트글10','21/06/01',0);
INSERT INTO REPLY_ON_LOSTDETAIL
VALUES(1,11,11,0,1,NULL,0,'ADMIN','테스트글11','21/06/01',0);
INSERT INTO REPLY_ON_LOSTDETAIL
VALUES(1,12,12,0,1,NULL,0,'ADMIN','테스트글12','21/06/01',0);
INSERT INTO REPLY_ON_LOSTDETAIL
VALUES(1,13,13,0,1,NULL,0,'ADMIN','테스트글13','21/06/01',0);
INSERT INTO REPLY_ON_LOSTDETAIL
VALUES(1,14,14,0,1,NULL,0,'ADMIN','테스트글14','21/06/01',0);
INSERT INTO REPLY_ON_LOSTDETAIL
VALUES(1,15,15,0,1,NULL,0,'ADMIN','테스트글15','21/06/01',0);
INSERT INTO REPLY_ON_LOSTDETAIL
VALUES(1,16,16,0,1,NULL,0,'ADMIN','테스트글16','21/06/01',0);
INSERT INTO REPLY_ON_LOSTDETAIL
VALUES(1,17,17,0,1,NULL,0,'ADMIN','테스트글17','21/06/01',0);
INSERT INTO REPLY_ON_LOSTDETAIL
VALUES(1,18,18,0,1,NULL,0,'ADMIN','테스트글18','21/06/01',0);

--------------------------

SELECT TARGET.*
FROM (SELECT BOARD_ID, REPLY_ORDER, NUM, LEV, LEVEL,LEV_SEQ, DEPTH,CONNECT_BY_ISLEAF ISLEAF, REPLYTAB, ID, CONTENT, REGDATE
FROM REPLY_ON_LOSTDETAIL
START WITH DEPTH IS NULL
CONNECT BY NOCYCLE PRIOR REPLY_ORDER=NUM
ORDER SIBLINGS BY LEV,LEV_SEQ) TARGET
WHERE BOARD_ID=1 AND NUM=18;

--DELETE FROM REPLY_ON_LOSTDETAIL WHERE BOARD_ID=1 AND NUM=17 AND LEV=1;

--각 레벨에 댓글이 몇 개가 있는지 확인
SELECT LEV, COUNT(REPLY_ORDER)
FROM   REPLY_ON_LOSTDETAIL
WHERE  BOARD_ID=1 AND NUM=8 AND LEV != 0
GROUP  BY LEV
ORDER  BY LEV;

--각 댓글에 몇개가 있는지 누적시켜서 확인 가능
SELECT LEV, SUM(COUNT(REPLY_ORDER)) OVER(ORDER BY LEV)
FROM   REPLY_ON_LOSTDETAIL
WHERE  BOARD_ID=1 AND NUM=18
GROUP  BY LEV
ORDER  BY LEV;

SELECT * FROM
(SELECT ROWNUM ORD, PROCESSED.* FROM
(SELECT TARGET.*
FROM (SELECT DISTINCT BOARD_ID, REPLY_ORDER, NUM, LEV,LEV_SEQ, REPLYTAB, ID, CONTENT, REGDATE, LIKENO, BAN
FROM REPLY_ON_LOSTDETAIL
START WITH LEV=0
CONNECT BY PRIOR LEV_SEQ= LEV
ORDER SIBLINGS BY LEV_SEQ) TARGET
WHERE NUM=12) PROCESSED)
WHERE (ORD BETWEEN 1 AND 30);


--DELETE FROM REPLY_ON_LOSTDETAIL;

SELECT * FROM
(SELECT ROWNUM ORD, PROCESSED.* FROM
(SELECT TARGET.*
FROM (SELECT BOARD_ID, REPLY_ORDER, NUM, LEV, LEV_SEQ, REPLYTAB, ID, CONTENT, REGDATE, LIKENO, BAN
FROM REPLY_ON_LOSTDETAIL
START WITH LEV=0
CONNECT BY PRIOR REPLY_ORDER= LEV
ORDER SIBLINGS BY LEV_SEQ) TARGET
WHERE NUM=14) PROCESSED)
WHERE (ORD BETWEEN 1 AND 30);

SELECT MAX(LEV) FROM REPLY_ON_LOSTDETAIL WHERE BOARD_ID=1 AND NUM=18;
SELECT LEV_SEQ FROM REPLY_ON_LOSTDETAIL WHERE BOARD_ID=1 AND NUM=18;